### ISSUE TITLE
Clearing up the database for classes that are not available in Admin or teacher's end are still shown under google classroom

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#163]

**Comment by montbit-tech** [comment]
How is it a critical bug? Is it impacting any operation or testing?

**Comment by ChitraQA** [comment]
@montbit-tech  It is creating ambiguity while creating new classes(and testing). For example, I am creating 12 A English. Although there wasn't any class earlier in the Admin system so it got created successfully. But in the classroom, I see there are more than 1 class on 12 A English which was created long back.

**Comment by montbit-tech** [comment]
Okay, in that case, since the tester is using Admin ID, you can delete all the classes in the Google Classroom. This is not being done programmatically hence manual intervention is needed.
The steps for the same are self-explanatory -> 
1. Click on the three dots in the top right corner of the class.
![image](https://user-images.githubusercontent.com/66239163/88933360-eb24a580-d29c-11ea-8d2e-c4d99c9521e5.png)
2. Click on Archive
![image](https://user-images.githubusercontent.com/66239163/88933454-0f808200-d29d-11ea-8249-942293c09479.png)
3. Go to Archived Class
![image](https://user-images.githubusercontent.com/66239163/88933521-26bf6f80-d29d-11ea-8698-c88940ae4cb0.png)
4. Select Delete from the options in the Archived class
![image](https://user-images.githubusercontent.com/66239163/88933644-53738700-d29d-11ea-836f-d1fd31860fa4.png)

Hope the issue is resolved now.
