### ISSUE TITLE
Developer Guidelines for the current and upcoming builds.

### ISSUE THREAD

**Issue by ChitraQA** [MontbitTech/WebApp-e-EdPort-LMS#166]
# Please do not modify the code for the test build "lms.schooltimes-s.ca" until specified

## Points to keep in mind while modifying the code for a bug fix or for an enhancement

- Please clarify the issue with the tester before proceeding to provide the fix or enhancement.
-  Do not alter the code or modify the functionalities in the current build where the issue has been found. (currently lms.schooltimes-s.ca). 
- Keep the modified or updated feature code for the bug fix or enhancement saved with yourself and implement it for the next build.
- The current build has to be kept intact and no further changes should be done in the code level (neither functionality nor UI changes). 

 # General

- Testers to test the current build and report the bugs. 
- Retesting the bugs will be done after a  new build is released with the bug fixes and enhancements.
- Developers to fix the code for the upcoming build and not to change the code for the current build.

>Please feel free to contact me if you have doubts on the above points 
> -Chitra

**Comment by krtrthbilory** [comment]
I thought we agreed on fixing while testing I don't see a big deal in fixing a bug when find one what you are suggesting will just increase the time of development this is not an app which needs versioning or releasing. The test env. which is lms.schooltimes-s.ca is for all yourself and the developers to final check for their bug fix or feature enhancement.  Well it's your call but I am not in favour of this @montbit-tech

**Comment by ParasRawat** [comment]
It does look easy from the developer perspective but it makes the system difficult to test. We are talking of 50 to 60 check points here. If you fix the code while we test it then we are often caught in a loop, testing same thing again and again, this way complete end to end testing of the product is missed. This happened last time, we started testing the things that you guys fixed on the go and therefore we were unable to cover some of the crucial parts associated with google classroom and others. It would be better if we have a finalized product for some time frame like about 3-6 days and we start listing bugs from day 1. These bugs you can concurrently improve in a new build.

**Comment by krtrthbilory** [comment]
you've got 2 days to test end to end and you were unable to do it. it was fine you could've asked more time but what I was aware that you guys were finished with all the bug testing after that only we started working on enhancements. Already talked about full system testing once in 2 weeks will give a fresh system for that but giving whole time for  testing delays the development. and if you check end to end for every new feature for 3-6 days just imagine how much time it's gonna take to develop a bug free system ?

**Comment by krtrthbilory** [comment]
I would never recommend it sorry

**Comment by krtrthbilory** [comment]
apart from this not pushing anything to the feature as you've asked but this is just a bad way to develop a web app

**Comment by ParasRawat** [comment]
2 days are not enough for us to conduct all the logic tests on this system.. . sometimes it even happens that a certain stable functionality which was there previously is not present now. For example time concurrency, same teacher is being assigned 2 different classes during same time slots on the same day. We though that this was a done deal as it was already constrained in the last build but today during the meeting call itself this issue appeared which was embarrassing because it was our duty to have tested it ..imagine such logical issues appearing in front of the client... so it was decided in the meeting itself... that for each build we will thoroughly check each and every part of our lms because we are not certain that a functionality that worked earlier is still working or not.... .we have created a list of certain checkpoints to go through before certifying a build for the client use...

**Comment by krtrthbilory** [comment]
great thanks for this... I was looking forward to this comment because I knew you'll bring this up whatever functionality you are talking about was working the same since the start I have looked into the code if you could understand the people who've written this code earlier have only checked for the exact time and not the time falling in between this issue was there earlier also and it's still there I would recommend to check in your live system before you say something like this. Yes adding new things adds some bugs and that's why I want someone to test thing as we push even I test when me or anyone from my team push some code.  And about time limit this is exactly what I said you could've asked for more time it was all okay but giving us free line to code with the testing and then stopping us in between in not right. The checkpoints or however you wanna work it's up to you but why it's taking so much time to deliver comes on me I have to take care of that.... I will recommend once you check live system as this is not the first time someone has told us that it was working in live system but not working here and I found that it was never working.

**Comment by ChitraQA** [comment]
@krtrthbilory We acknowledge your points and these can be taken into consideration for further builds, we will shorten the testing and development/bug fixing time span and keep them frequent and separate as well (for example we can give you some time of the day to deploy the code in the testing build and that time we will halt the testing). 
For now, let's stick to what's been planned. Paras and I are testing this build and we will update you on the completion of our round of testing(most probably the next Monday) and then you can start patching up the modifications.
Thanks

**Comment by krtrthbilory** [comment]
@ChitraQA  the response I was expecting thankyou so much you can let us know when you finished
